title: Flarfnoogins
author: "Derek Wyatt"
header-img: img/orion-nebula-space-galaxy.jpg
email: derek@derekwyatt.org
description: "Vim, Scala, and cody things"
baseurl: ""
url: http://derekwyatt.github.io
twitter_username: derekwyatt
github_username: derekwyatt
linkedin_username: derekqwyatt

# Build settings
highlighter: rouge
permalink: pretty
exclude: ["Gemfile", "Gemfile.lock", "less", "README.md"]
