name: Flarfnoogins
author: Derek Wyatt
description: Vim, Scala, and cody things
url: http://derekwyatt.github.io
safe: false
lsi: false
pygments: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock', 'bin/work', 'bin/fswatcher', 'db.dump.gz', 'derekwyatt.org.tgz']
